# Generated by Django 2.2.3 on 2019-07-21 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='functions_db_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('function', models.CharField(blank=True, max_length=250, verbose_name='Функция')),
                ('result_function', models.ImageField(blank=True, default=0, editable=False, upload_to='images', verbose_name='График')),
                ('interval', models.IntegerField(blank=True, default=0, null=True, verbose_name='Интервал t, дней')),
                ('dt', models.IntegerField(blank=True, default=0, null=True, verbose_name='Шаг t, часы')),
                ('date_of_processing', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, verbose_name='Дата обработки')),
                ('error', models.CharField(blank=True, default=0, editable=False, max_length=500)),
            ],
        ),
    ]
